language: cpp

sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: gcc
      dist: trusty
    - os: linux
      compiler: gcc
      dist: trusty
      env: DPDK_VER=16.11.1      

addons:
  apt:
    packages:
    - libpcap-dev
    - net-tools

before_script:
  - if [[ "$DPDK_VER" == "16.11.1" ]]; then Deploy/build-dpdk.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./configure-mac_os_x.sh      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./configure-linux.sh --default; fi
  - make all
  
script:
  - cd Tests/Packet++Test
  - Bin/Packet++Test
  - cd ../Pcap++Test
  - sudo Bin/Pcap++Test -n
