language: cpp

sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: gcc
      dist: trusty
    - os: linux
      compiler: gcc
      dist: trusty
      env: 
        - DPDK_VER=16.11.1
        - DPDK_DIR=dpdk-stable-16.11.1
    - os: linux
      compiler: gcc
      dist: trusty
      env: 
        - DPDK_VER=17.02
        - DPDK_DIR=dpdk-17.02

addons:
  apt:
    packages:
    - libpcap-dev
    - net-tools

before_script:
  - ifconfig
  - if [[ ! -z $DPDK_VER ]]; then chmod +x Deploy/build-dpdk.sh; fi
  - if [[ ! -z $DPDK_VER ]]; then Deploy/build-dpdk.sh $DPDK_VER $DPDK_DIR; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./configure-mac_os_x.sh      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./configure-linux.sh --default; fi
  - if [[ ! -z $DPDK_VER  ]]; then ./configure-linux.sh --dpdk --dpdk-home /home/travis/build/seladb/PcapPlusPlus/$DPDK_DIR; fi
  - make all
  
script:
  - cd Tests/Packet++Test
  - Bin/Packet++Test
  - cd ../Pcap++Test
  - sudo Bin/Pcap++Test -n -k 0
