language: cpp

sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: gcc
      dist: trusty

addons:
  apt:
    packages:
    - libpcap-dev
    - net-tools
    - libncurses-dev
    - linux-headers-3.13.0-40-generic

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./configure-mac_os_x.sh      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./configure-linux.sh --default; fi
  - make all
  
script:
  - cd Tests/Packet++Test
  - Bin/Packet++Test
  - cd ../Pcap++Test
  - sudo Bin/Pcap++Test -n
