language: cpp

sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: gcc
      dist: trusty
    - os: linux
      compiler: gcc
      dist: trusty
      env: DPDK_VER=16.11.1

addons:
  apt:
    packages:
    - libpcap-dev
    - net-tools
    - linux-headers-4.4.0-51-generic

before_script:
  - ifconfig
  - if [[ "$DPDK_VER" == "16.11.1" ]]; then chmod +x Deploy/build-dpdk.sh; fi
  - if [[ "$DPDK_VER" == "16.11.1" ]]; then Deploy/build-dpdk.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./configure-mac_os_x.sh      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./configure-linux.sh --default; fi
  - if [[ "$DPDK_VER" == "16.11.1" ]]; then ./configure-linux.sh --dpdk --dpdk-home /home/travis/build/seladb/PcapPlusPlus/dpdk-stable-16.11.1; fi
  - make all
  - if [[ "$DPDK_VER" == "16.11.1" ]]; then ./setup-dpdk.sh -p 256 -n eth0; fi
  
script:
  - cd Tests/Packet++Test
  - Bin/Packet++Test
  - cd ../Pcap++Test
  - sudo Bin/Pcap++Test -n
